### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by joyrexus** [nmaquet/kasper#14]
Greetings. I read your intro [blog post](https://movio.co/en/blog/Kasper-process-library/) and [talk](https://nmaquet.github.io/kasper-talk-go-akl/#/).

Very intrigued by this project (as well as [goka](https://github.com/lovoo/goka)), but noticed that it's still in beta and doesn't seem to be under active development.

So, curious ... are you still using it in production? Did the micro-batching / centralized state-management design prove to be problematic?

**Comment by wood-jp** [comment]
I would also like to know where things stand.

**Comment by nmaquet** [comment]
Hey @joyrexus, @wood-jp 

You are correct, Kasper is not currently in active development. We created Kasper as an alternative to Samza for stream processing, but have since decided to avoid using stream processing whenever possible. This isn't due to the micro-batching / centralized state-management design but rather the fact that we are moving away from stream processing altogether.

Going forward, we will address any bugs or issues in Kasper and we certainly do welcome contributions.

**Comment by allyraza** [comment]
Hi @nmaquet,

can i ask you the reason for moving away from stream processing is it because you guys don't have a use case for it anymore or some other reason

**Comment by nmaquet** [comment]
Hey @allyraza, 

Here's how I would break it down:

- 99% of our data processing uses cases don't require low-latency but rather high throughput
- we have found empirically that creating a streaming analytics system is about an order of magnitude more difficult in terms of development and maintainability than the equivalent batch-oriented system
- we have started using Spark on Hadoop for most of our batch heavy lifting, and found that we could build very efficient systems very quickly using those tools

Happy to answer further questions on this subject if you have any.
