### ISSUE TITLE
Stores should return interface

### ISSUE THREAD

**Issue by jhaynie** [nmaquet/kasper#9]
You're defining two interfaces `Map` and `MultiMap` but in the concrete implementation of `Redis` in the functions `NewMultiRedis` and `NewRedis` you're returning internal structure instead of the interface (`MultiStore` and `Store` respectfully).  Same for elasticsearch.

This makes it difficult to leverage the interface when swapping out Store implementations.

For example, instead of:

```
func NewRedis(config *Config, conn redis.Conn, keyPrefix string) *Redis
```

It should be:

```
func NewRedis(config *Config, conn redis.Conn, keyPrefix string) Store
```

Since the `Redis` struct implements the `Store` interface.

If a user would like to use the concrete implementation (for some reason), they can always do something like the following to check the implementation and cast:

```
if r, ok := thestore.(*Redis); ok {
}
```

If we can make this change, it will make it much easier to actually use different implementations of these interfaces.

I'm happy to submit a PR if you'd like.

**Comment by nmaquet** [comment]
I'm still a relative beginner in Go but I believe what your suggesting goes against the general Go guideline of ["accept interfaces, return structs"](http://idiomaticgo.com/post/best-practice/accept-interfaces-return-structs/).

Taking your example of the Redis implementation, since `*Redis` implements the `Store` interface, you can use that reference as if it were any other `Store` without issue. Your code can, of course, call Redis-specific methods also and break this compatibility (there aren't any thus far, but there may be in the future).

If you want to avoid coupling your code to specific `Store` implementations, I believe the simplest solution is to declare it explicitly:

```
var store kasper.Store
store = kasper.NewRedis(conf, conn, keyPrefix)
```

Let me know if I missed something.

**Comment by jhaynie** [comment]
@nmaquet you're absolutely right and i'm an idiot. I think what happened is when i ran one of your examples i used the wrong type and that's why the compiler complained and i immediately thought that was an issue.  You can close this. This is implemented in the canonical go way and i just wasn't thinking (it was late, sorry).

**Comment by nmaquet** [comment]
No worries! Cheers :)
